CFLAGS=-g -Wall -Werror -std=gnu99 -pedantic
break_all: break_all.c
	gcc $(CFLAGS) -o break_all break_all.c
#break: break.c
#	gcc $(CFLAGS) -o break break.c
#break_debug: break_debug.c
#	gcc $(CFLAGS) -o break_debug break_debug.c
