Q13.8_plus_cp2: Q13.8_plus_cp2.c
	gcc -g -o Q13.8_plus_cp2 -pedantic -std=gnu99 -Wall -Werror Q13.8_plus_cp2.c
#Q13.8_plus: Q13.8_plus.c
#	gcc -g -o Q13.8_plus -pedantic -std=gnu99 -Wall -Werror Q13.8_plus.c
