all:
	gcc -g -o fileSum -pedantic -std=gnu99 -Wall -Werror Q11.8.c
	#gcc -g -o myCp3 -pedantic -std=gnu99 -Wall -Werror Q11.7.c
	#gcc -g -o myCp2 -pedantic -std=gnu99 -Wall -Werror Q11.6.c
	#gcc -g -o myCat -pedantic -std=gnu99 -Wall -Werror Q11.3.c
	#gcc -g -o myCat2 -pedantic -std=gnu99 -Wall -Werror Q11.4.c
	#gcc -g -o myCp -pedantic -std=gnu99 -Wall -Werror Q11.5.c
