CPPFLAGS=-std=gnu++98 -pedantic -Wall -Werror -ggdb3
Q15.7: Q15.7.o
	g++ -o Q15.7 Q15.7.o
#main.o: main.cpp
#	g++ $(CPPFLAGS) -c main.cpp
#vector.o: vector.cpp vector.hpp
#	g++ $(CPPFLAGS) -c vector.cpp

.PHONY: clean
clean:
	rm -f *.o *~ vector2d
