all:
	#gcc -std=gnu99 -ggdb3 -o fibonacii fibonacii.c
	#gcc -Wall -std=gnu99 -ggdb3 -o factorial factorial.c
	gcc -Wall -std=gnu99 -ggdb3 -o q7.7 Q7.7.c
	gcc -Wall -std=gnu99 -ggdb3 -o test_char test_char.c

